version: "2"

volumes:
  gems:
    driver: local

services:
  belugas_python:
    image: gueils/belugas-python:development
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: bash
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
      - /home/eduardo/Documentos/REPOS/django-postgres-copy:/code
    stdin_open: true
    tty: true
